### ISSUE TITLE
Could not create ISO

### ISSUE THREAD

**Issue by biconix** [WOA-Project/guides#1]
I was able to download the "creatingISO_17763.346_en-us_arm64_Professional.cmd" file but was not able to execute it.
after it downloads a bunch of files, the screen clears and I get an error that says: "Error work script.".
Am I leaving something out?
(I have downloaded to script file to c:\temp\WindowsARM folder)

**Comment by biconix** [comment]
no zip file is downloaded, just a CMD: even though the instructions say:
Please, notice the we selected the ARM64 architecture (not to confuse with AMD64)
You can select a newer build if you wish. Take into account, however, that each build can have some issues. It's recommended to select builds from the R5+ branch. Build numbers like 18XXX are usually OK.
Click the link on the right. It will appear when you've done selecting the options. **_It will download a .zip file._**
Extract the .zip file to a Folder, preferably one that doesn't contain spaces in the path, like "c:\temp\W10IsoScripts"
Execute the script creatingISO.cmd and wait for it to complete.
When the script has finished, you will find a .iso inside, as a result of the process.
Mount the .iso file with Windows Explorer by double clicking it.
Navigate to the folder x:\sources, where x: is the drive letter of the mounted .iso file.
Inside this "sources" folder you will find the install.wim that WoA Installer needs to deploy Windows

**Comment by cleveHEX** [comment]
Do NOT open the same issue everywhere! I might ban you in the future.

**Comment by SuperJMN** [comment]
@biconix use this: https://uupdump.ml

**Comment by biconix** [comment]
My apologies. I saw that the case was closed without explanation so I thought it was because I posted it to the wrong place


_____________________________________________________________________
Moshe Raab, Ph.D.
Microsoft Certified Professional
Microsoft Certified Technology Specialist – Microsoft Dynamics CRM
Biconix, Inc., mailto:raab@biconix.com,
(USA)  +1 (561) 208-3858
(Israel) +972(2) 590-0801

**Comment by George-PR** [comment]
I had the same issue. 
On [uup.rg-adguard.net](url), choosing "feature update to Windows 10, version 1809 arm64 2019-03 [arm64]" worked ok.

**Comment by SuperJMN** [comment]
@George-PR This is for issues with WOA Deployer, not ISO-creating scripts
