### ISSUE TITLE
script to create iso wipe my folder Download

### ISSUE THREAD

**Issue by x0rld** [WOA-Project/guides#2]
i got many files in my folder Download the script said this 
![image](https://user-images.githubusercontent.com/45242856/54887996-4a98c700-4e99-11e9-8f1e-76c0140134ad.png)

then auto remove and remove all of my download folder
![image](https://user-images.githubusercontent.com/45242856/54888008-600df100-4e99-11e9-8428-1c4c9d25d4b7.png)

**Comment by cleveHEX** [comment]
This script was not made by us, you can try data recovery software.
