### ISSUE TITLE
C: merged with ISO?

### ISSUE THREAD

**Issue by t3chn0T33n-zz** [WOA-Project/guides#8]
I don't know what to do. it stopped at:
 Processing 1 of 1 - Adding package Package_for_RollupFix~31bf3856ad364e35~arm64~~18970.1005.1.0
[===========================69.0%========                  ]

Nice. but really i'm kinda scared.
my C: drive is all messed up. 
and i kinda don't know what i'm doing, all i know is that this should be easy. it is but i'm kinda scared.

**Comment by cleveHEX** [comment]
This is not issue tracker of tools, I am not even sure what do you you mean by messed up C: drive.
